package com.ontraport.mobileapp.main.record.views;

import android.view.View;
import com.ontraport.mobileapp.main.record.asynctasks.UpdateAsyncTask;
import com.ontraport.sdk.http.Meta;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CountryViewHolder extends DropDownViewHolder {

    public CountryViewHolder(View view) {
        super(view);
    }

    @Override
    public void fetchData(String field, String field_value) {
        Meta.Field meta_field = getMetaForField(field);
        if (meta_field.getType().equals("country")) {
            Map<String, String> options = getCountryMap();
            List<String> values = new ArrayList<>(options.values());
            populateDropdown(values);
            setDefaultValue(values.indexOf(options.get(field_value)) + 1);
        }
    }

    @Override
    protected void doUpdate(String field, String new_val) {
        Map<String, String> options = getCountryMap();
        for (Map.Entry<String, String> entry : options.entrySet()) {
            if (entry.getValue().equals(new_val)) {
                new_val = entry.getKey();
                break;
            }
        }

        if (!new_val.equals(old_val)) {
            super.doUpdate(field, new_val);
            old_val = new_val;
            params.put(field, new_val);
            new UpdateAsyncTask(view.getContext()).execute(params);
        }
    }

    private Map<String, String> getCountryMap() {
        Map<String, String> map = new HashMap<>();
        map.put("US", "United States");
        map.put("CA", "Canada");
        map.put("GB", "United Kingdom");
        map.put("AF", "Afghanistan");
        map.put("AX", "Åland");
        map.put("AL", "Albania");
        map.put("DZ", "Algeria");
        map.put("AS", "American Samoa");
        map.put("AD", "Andorra");
        map.put("AO", "Angola");
        map.put("AI", "Anguilla");
        map.put("AQ", "Antarctica");
        map.put("AG", "Antigua and Barbuda");
        map.put("AR", "Argentina");
        map.put("AM", "Armenia");
        map.put("AW", "Aruba");
        map.put("AU", "Australia");
        map.put("AT", "Austria");
        map.put("AZ", "Azerbaijan");
        map.put("BS", "Bahamas");
        map.put("BH", "Bahrain");
        map.put("BD", "Bangladesh");
        map.put("BB", "Barbados");
        map.put("BY", "Belarus");
        map.put("BE", "Belgium");
        map.put("BZ", "Belize");
        map.put("BJ", "Benin");
        map.put("BM", "Bermuda");
        map.put("BT", "Bhutan");
        map.put("BO", "Bolivia");
        map.put("BQ", "Bonaire");
        map.put("BA", "Bosnia and Herzegovina");
        map.put("BW", "Botswana");
        map.put("BV", "Bouvet Island");
        map.put("BR", "Brazil");
        map.put("IO", "British Indian Ocean Territory");
        map.put("VG", "British Virgin Islands");
        map.put("BN", "Brunei");
        map.put("BG", "Bulgaria");
        map.put("BF", "Burkina Faso");
        map.put("BI", "Burundi");
        map.put("KH", "Cambodia");
        map.put("CM", "Cameroon");
        map.put("CV", "Cape Verde");
        map.put("KY", "Cayman Islands");
        map.put("CF", "Central African Republic");
        map.put("TD", "Chad");
        map.put("CL", "Chile");
        map.put("CN", "China");
        map.put("CX", "Christmas Island");
        map.put("CC", "Cocos (Keeling) Islands");
        map.put("CO", "Colombia");
        map.put("KM", "Comoros");
        map.put("CK", "Cook Islands");
        map.put("CR", "Costa Rica");
        map.put("HR", "Croatia (Local Name: Hrvatska)");
        map.put("CU", "Cuba");
        map.put("CW", "Curacao");
        map.put("CY", "Cyprus");
        map.put("CZ", "Czech Republic");
        map.put("CD", "Democratic Republic of the Congo");
        map.put("DK", "Denmark");
        map.put("DJ", "Djibouti");
        map.put("DM", "Dominica");
        map.put("DO", "Dominican Republic");
        map.put("TL", "East Timor");
        map.put("EC", "Ecuador");
        map.put("EG", "Egypt");
        map.put("SV", "El Salvador");
        map.put("GQ", "Equatorial Guinea");
        map.put("ER", "Eritrea");
        map.put("EE", "Estonia");
        map.put("ET", "Ethiopia");
        map.put("FK", "Falkland Islands (Malvinas)");
        map.put("FO", "Faroe Islands");
        map.put("FJ", "Fiji");
        map.put("FI", "Finland");
        map.put("FR", "France");
        map.put("GF", "French Guiana");
        map.put("PF", "French Polynesia");
        map.put("TF", "French Southern Territories");
        map.put("GA", "Gabon");
        map.put("GM", "Gambia");
        map.put("GE", "Georgia");
        map.put("DE", "Germany");
        map.put("GH", "Ghana");
        map.put("GI", "Gibraltar");
        map.put("GR", "Greece");
        map.put("GL", "Greenland");
        map.put("GD", "Grenada");
        map.put("GP", "Guadeloupe");
        map.put("GU", "Guam");
        map.put("GT", "Guatemala");
        map.put("GG", "Guernsey");
        map.put("GN", "Guinea");
        map.put("GW", "Guinea-Bissau");
        map.put("GY", "Guyana");
        map.put("HT", "Haiti");
        map.put("HM", "Heard Island and McDonald Islands");
        map.put("HN", "Honduras");
        map.put("HK", "Hong Kong");
        map.put("HU", "Hungary");
        map.put("IS", "Iceland");
        map.put("IN", "India");
        map.put("ID", "Indonesia");
        map.put("IR", "Iran");
        map.put("IQ", "Iraq");
        map.put("IE", "Ireland");
        map.put("IM", "Isle of Man");
        map.put("IL", "Israel");
        map.put("IT", "Italy");
        map.put("CI", "Ivory Coast");
        map.put("JM", "Jamaica");
        map.put("JP", "Japan");
        map.put("JE", "Jersey");
        map.put("JO", "Jordan");
        map.put("KZ", "Kazakhstan");
        map.put("KE", "Kenya");
        map.put("KI", "Kiribati");
        map.put("XK", "Kosovo");
        map.put("KW", "Kuwait");
        map.put("KG", "Kyrgyzstan");
        map.put("LA", "Laos");
        map.put("LV", "Latvia");
        map.put("LB", "Lebanon");
        map.put("LS", "Lesotho");
        map.put("LR", "Liberia");
        map.put("LY", "Libya");
        map.put("LI", "Liechtenstein");
        map.put("LT", "Lithuania");
        map.put("LU", "Luxembourg");
        map.put("MO", "Macao");
        map.put("MK", "Macedonia");
        map.put("MG", "Madagascar");
        map.put("MW", "Malawi");
        map.put("MY", "Malaysia");
        map.put("MV", "Maldives");
        map.put("ML", "Mali");
        map.put("MT", "Malta");
        map.put("MH", "Marshall Islands");
        map.put("MQ", "Martinique");
        map.put("MR", "Mauritania");
        map.put("MU", "Mauritius");
        map.put("YT", "Mayotte");
        map.put("MX", "Mexico");
        map.put("FM", "Micronesia");
        map.put("MD", "Moldova");
        map.put("MC", "Monaco");
        map.put("MN", "Mongolia");
        map.put("ME", "Montenegro");
        map.put("MS", "Montserrat");
        map.put("MA", "Morocco");
        map.put("MZ", "Mozambique");
        map.put("MM", "Myanmar (Burma)");
        map.put("NA", "Namibia");
        map.put("NR", "Nauru");
        map.put("NP", "Nepal");
        map.put("NL", "Netherlands");
        map.put("NC", "New Caledonia");
        map.put("NZ", "New Zealand");
        map.put("NI", "Nicaragua");
        map.put("NE", "Niger");
        map.put("NG", "Nigeria");
        map.put("NU", "Niue");
        map.put("NF", "Norfolk Island");
        map.put("KP", "North Korea");
        map.put("MP", "Northern Mariana Islands");
        map.put("NO", "Norway");
        map.put("OM", "Oman");
        map.put("PK", "Pakistan");
        map.put("PW", "Palau");
        map.put("PS", "Palestine");
        map.put("PA", "Panama");
        map.put("PG", "Papua New Guinea");
        map.put("PY", "Paraguay");
        map.put("PE", "Peru");
        map.put("PH", "Philippines");
        map.put("PN", "Pitcairn Islands");
        map.put("PL", "Poland");
        map.put("PT", "Portugal");
        map.put("PR", "Puerto Rico");
        map.put("QA", "Qatar");
        map.put("CG", "Republic of the Congo");
        map.put("RE", "Réunion");
        map.put("RO", "Romania");
        map.put("RU", "Russia");
        map.put("RW", "Rwanda");
        map.put("BL", "Saint Barthélemy");
        map.put("SH", "Saint Helena");
        map.put("KN", "Saint Kitts and Nevis");
        map.put("LC", "Saint Lucia");
        map.put("MF", "Saint Martin");
        map.put("PM", "Saint Pierre and Miquelon");
        map.put("VC", "Saint Vincent and the Grenadines");
        map.put("WS", "Samoa");
        map.put("SM", "San Marino");
        map.put("SA", "Saudi Arabia");
        map.put("SN", "Senegal");
        map.put("RS", "Serbia");
        map.put("SC", "Seychelles");
        map.put("SL", "Sierra Leone");
        map.put("SG", "Singapore");
        map.put("SX", "Sint Maarten");
        map.put("SK", "Slovakia (Slovak Republic)");
        map.put("SI", "Slovenia");
        map.put("SB", "Solomon Islands");
        map.put("SO", "Somalia");
        map.put("ZA", "South Africa");
        map.put("GS", "South Georgia and the South Sandwich Islands");
        map.put("KR", "South Korea");
        map.put("SS", "South Sudan");
        map.put("ES", "Spain");
        map.put("LK", "Sri Lanka");
        map.put("SD", "Sudan");
        map.put("SR", "Suriname");
        map.put("SJ", "Svalbard and Jan Mayen");
        map.put("SZ", "Swaziland");
        map.put("SE", "Sweden");
        map.put("CH", "Switzerland");
        map.put("SY", "Syria");
        map.put("ST", "São Tomé and Príncipe");
        map.put("TW", "Taiwan");
        map.put("TJ", "Tajikistan");
        map.put("TZ", "Tanzania");
        map.put("TH", "Thailand");
        map.put("TG", "Togo");
        map.put("TK", "Tokelau");
        map.put("TO", "Tonga");
        map.put("TT", "Trinidad and Tobago");
        map.put("TN", "Tunisia");
        map.put("TR", "Turkey");
        map.put("TM", "Turkmenistan");
        map.put("TC", "Turks and Caicos Islands");
        map.put("TV", "Tuvalu");
        map.put("UM", "U.S. Minor Outlying Islands");
        map.put("VI", "U.S. Virgin Islands");
        map.put("UG", "Uganda");
        map.put("UA", "Ukraine");
        map.put("AE", "United Arab Emirates");
        map.put("UY", "Uruguay");
        map.put("UZ", "Uzbekistan");
        map.put("VU", "Vanuatu");
        map.put("VA", "Vatican City");
        map.put("VE", "Venezuela");
        map.put("VN", "Vietnam");
        map.put("WF", "Wallis and Futuna");
        map.put("EH", "Western Sahara");
        map.put("YE", "Yemen");
        map.put("ZM", "Zambia");
        map.put("ZW", "Zimbabwe");
        return map;
    }
}
